# Generated by Django 4.1.7 on 2023-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PROTECTED', 'PROTECTED'), ('ACTIVE', 'ACTIVE'), ('REPORTED', 'REPORTED')], default='ACTIVE', max_length=20, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
