# Generated by Django 4.1.7 on 2023-05-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_post_status_post_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
