# Generated by Django 4.1.7 on 2023-07-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=5, null=True, verbose_name='이름'),
        ),
    ]
