# Generated by Django 4.1.7 on 2023-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='login_fail',
            field=models.IntegerField(default=0),
        ),
    ]
